// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<TConstruct:heartCanister:4>);
recipes.remove(<TConstruct:heartCanister:2>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<TConstruct:diamondApple> * 4, [[null, <ore:listAllfruit>, null], [<minecraft:apple>, <minecraft:diamond>, <ore:listAllfruit>], [null, <minecraft:apple>, null]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<TConstruct:slime.channel>, [<TConstruct:slime.gel:*>, <TConstruct:buckets:24>.giveBack(<minecraft:bucket>)]);
recipes.addShapeless(<minecraft:skull:2>, [<minecraft:skull>]);
recipes.addShapeless(<minecraft:skull>, [<minecraft:skull:2>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<TConstruct:slime.channel>, [[<ore:slimeball>, <ore:slimeball>], [<ore:slimeball>, <ore:slimeball>], [<TConstruct:buckets:24>.giveBack(<minecraft:bucket>), null]]);
recipes.addShaped(<OpenBlocks:tank>, [[<minecraft:stone>, <ore:paneGlassColorless>, <minecraft:stone>], [<ore:paneGlassColorless>, <ore:paneGlassColorless>, <ore:paneGlassColorless>], [<minecraft:stone>, <ore:paneGlassColorless>, <minecraft:stone>]]);
recipes.addShaped(<TConstruct:diamondApple> * 4, [[null, <minecraft:apple>, null], [<minecraft:apple>, <ore:gemDiamond>, <minecraft:apple>], [null, <minecraft:apple>, null]]);
recipes.addShaped(<TConstruct:materials:8>, [[null, <minecraft:bone>, null], [<minecraft:bone>, <GraveStone:GSSkullCandle>, <minecraft:bone>], [null, <minecraft:bone>, null]]);
recipes.addShaped(<TConstruct:heartCanister:1>, [[null, <minecraft:rotten_flesh>, null], [<minecraft:rotten_flesh>, <GraveStone:GSSkullCandle:2>, <minecraft:rotten_flesh>], [null, <minecraft:rotten_flesh>, null]]);
recipes.addShaped(<TConstruct:heartCanister:4>, [[null, <TConstruct:heartCanister:2>, null], [<minecraft:golden_carrot>, <TConstruct:heartCanister:3>, <minecraft:speckled_melon>]]);
recipes.addShaped(<TConstruct:heartCanister:3>, [[null, <TConstruct:materials:8>, null], [<TConstruct:heartCanister:1>, <GraveStone:GSCandle>, <TConstruct:heartCanister:1>], [null, <TConstruct:materials:8>, null]]);
recipes.addShaped(<TConstruct:heartCanister:5>, [[null, <TConstruct:heartCanister:3>, null], [<minecraft:golden_apple>, <minecraft:skull:4>, <minecraft:golden_apple>], [null, <TConstruct:materials:26>, null]]);
recipes.addShaped(<TConstruct:heartCanister:6>, [[null, <TConstruct:heartCanister:4>, null], [<ore:nuggetUnstable>, <TConstruct:heartCanister:5>, <ore:nuggetUnstable>]]);
recipes.addShaped(<TConstruct:heartCanister:2>, [[null, <TConstruct:diamondApple>, null], [<TConstruct:materials:8>, <TConstruct:heartCanister>, <TConstruct:heartCanister:1>]]);

